# geochat_sdk/plugin.py
from __future__ import annotations

import inspect
import typing
from typing import Any, Callable, get_type_hints

from geochat_kernel.contracts.planner import BasePlanner
from geochat_kernel.contracts.plugin import BasePlugin
from geochat_kernel.contracts.result_fusion import BaseResultFusion
from geochat_kernel.contracts.step_handler import BaseStepHandler
from geochat_kernel.models.execution_artifact import ExecutionArtifact
from geochat_kernel.models.geo_response import GeoResponse
from geochat_kernel.models.manifest import PluginManifest
from geochat_kernel.models.query_ir import QueryIR
from geochat_kernel.models.query_plan import PlanStep, QueryPlan
from geochat_kernel.runtime.execution_context import ExecutionContext

from geochat_sdk.decorators import CapabilityRegistration, _PENDING_CAPABILITIES
from geochat_sdk.types.raster import RasterIn, RasterOut
from geochat_sdk.types.vector import VectorIn, VectorOut


class SDKStepHandler(BaseStepHandler):
    """
    Dynamic Step Handler generated by the SDK.
    Performs automatic type coercion for arguments and return values.
    """

    def __init__(self, plugin_id: str, reg: CapabilityRegistration) -> None:
        self._plugin_id = plugin_id
        self._reg = reg
        self._step_type = f"sdk.{plugin_id}.{reg.name}"

    @property
    def name(self) -> str:
        return f"handler_{self._plugin_id}_{self._reg.func.__name__}"

    @property
    def handled_types(self) -> list[str]:
        return [self._step_type]

    @property
    def priority(self) -> int:
        return 100

    async def handle(
        self,
        step: PlanStep,
        inputs: dict[str, ExecutionArtifact],
        context: ExecutionContext,
    ) -> ExecutionArtifact:
        sig = inspect.signature(self._reg.func)
        kwargs: dict[str, Any] = {}

        # ── کلید اصلاح: resolve کردن annotation‌های رشته‌ای به نوع واقعی ──
        try:
            resolved_hints = get_type_hints(self._reg.func)
        except Exception:
            # اگر resolve ناموفق بود، از annotation خام استفاده می‌کنیم
            resolved_hints = {
                p: param.annotation
                for p, param in sig.parameters.items()
                if param.annotation is not inspect.Parameter.empty
            }

        for param_name, param in sig.parameters.items():
            # annotation واقعی (نه رشته) را از resolved_hints می‌گیریم
            annotation = resolved_hints.get(param_name, param.annotation)

            # 1. Map context
            if annotation is ExecutionContext or param_name == "context":
                kwargs[param_name] = context
                continue

            # 2. Map RasterIn
            if annotation is RasterIn:
                art = inputs.get(param_name)
                if not art:
                    art = next((a for a in inputs.values() if a.kind == "raster_ref"), None)
                if not art:
                    available = context.metadata.get("available_inputs", [])
                    if param_name in available or any(param_name in str(x) for x in available) or "band" in param_name:
                        art = ExecutionArtifact.of_payload(
                            kind="raster_ref",
                            payload={"path": f"data/{param_name}.tif", "name": param_name, "virtual": True},
                            produced_by="sdk_context_resolver",
                        )
                    else:
                        raise ValueError(f"Missing raster input for argument '{param_name}'")
                kwargs[param_name] = RasterIn(art)
                continue

            # 3. Map VectorIn
            if annotation is VectorIn:
                art = inputs.get(param_name)
                if not art:
                    art = next((a for a in inputs.values() if a.kind in ("features", "vector")), None)
                if not art:
                    available = context.metadata.get("available_inputs", [])
                    if param_name in available or any(param_name in str(x) for x in available):
                        art = ExecutionArtifact.of_payload(
                            kind="features",
                            payload={"features": [], "name": param_name, "virtual": True},
                            produced_by="sdk_context_resolver",
                        )
                    else:
                        raise ValueError(f"Missing vector input for argument '{param_name}'")
                kwargs[param_name] = VectorIn(art)
                continue

            # 4. Map primitives from step parameters
            if param_name in step.parameters:
                kwargs[param_name] = step.parameters[param_name]
            elif param.default is not inspect.Parameter.empty:
                kwargs[param_name] = param.default
            else:
                raise ValueError(
                    f"Missing parameter '{param_name}' required by capability '{self._reg.name}'."
                )

        # Execute target capability
        if inspect.iscoroutinefunction(self._reg.func):
            result = await self._reg.func(**kwargs)
        else:
            result = self._reg.func(**kwargs)

        # Coerce output back to ExecutionArtifact
        if isinstance(result, RasterOut):
            return result.to_artifact(produced_by=self.name)
        if isinstance(result, VectorOut):
            return result.to_artifact(produced_by=self.name)
        if isinstance(result, ExecutionArtifact):
            return result

        # Default fallback
        return ExecutionArtifact.of_payload(
            kind="payload",
            payload={"result": result},
            produced_by=self.name,
        )


class SDKPlanner(BasePlanner):
    """
    Dynamic Planner generated by the SDK.
    Routes queries to the generated Step Handler.
    """

    def __init__(self, plugin_id: str, reg: CapabilityRegistration) -> None:
        self._plugin_id = plugin_id
        self._reg = reg
        self._step_type = f"sdk.{plugin_id}.{reg.name}"

    @property
    def name(self) -> str:
        return f"planner_{self._plugin_id}_{self._reg.func.__name__}"

    @property
    def priority(self) -> int:
        return 100

    def match_score(self, query_ir: QueryIR, context: ExecutionContext) -> float:
        routing = context.metadata.get("routing") or {}
        selected = routing.get("selected") or []
        if self._reg.name in selected:
            return 1.0

        raw = (query_ir.raw_text or "").lower()
        if any(kw.lower() in raw for kw in self._reg.keywords):
            return 0.8

        return 0.0

    async def build_plan(self, query_ir: QueryIR, context: ExecutionContext) -> QueryPlan:
        params: dict[str, Any] = {}
        for entity in query_ir.entities:
            params[entity.role] = entity.name

        if query_ir.constraints.radius_m:
            params["radius_m"] = query_ir.constraints.radius_m
        if query_ir.constraints.limit:
            params["limit"] = query_ir.constraints.limit

        step = PlanStep(
            type=self._step_type,
            name=f"step_{self._reg.name}",
            parameters=params,
            metadata={"plugin_id": self._plugin_id},
        )

        return QueryPlan(
            query_ir_id=query_ir.id,
            steps=[step],
            metadata={"plugin_id": self._plugin_id, "source": self._plugin_id},
        )


class SDKResultFusion(BaseResultFusion):
    """
    Default dynamic result fusion for SDK plugins.
    """

    def __init__(self, plugin_id: str) -> None:
        self._plugin_id = plugin_id

    @property
    def name(self) -> str:
        return f"fusion_{self._plugin_id}"

    @property
    def priority(self) -> int:
        return 100

    def match_score(
        self,
        query_ir: QueryIR,
        plan: QueryPlan,
        artifacts: dict[str, ExecutionArtifact],
        context: ExecutionContext,
    ) -> float:
        if plan.metadata.get("plugin_id") == self._plugin_id:
            return 1.0
        return 0.0

    async def fuse(
        self,
        query_ir: QueryIR,
        plan: QueryPlan,
        artifacts: dict[str, ExecutionArtifact],
        context: ExecutionContext,
    ) -> GeoResponse:
        response = GeoResponse.success(
            query_ir_id=query_ir.id,
            request_id=context.request_id,
        )
        response.metadata["plugin_id"] = self._plugin_id
        response.metadata["source"] = self._plugin_id

        has_features = False
        for art in artifacts.values():
            if art.kind == "features":
                features_list = art.payload.get("features", [])
                from geochat_kernel.models.feature_group import FeatureGroup
                from geochat_kernel.models.geo_feature import GeoFeature

                f_objs = [GeoFeature.from_dict(f) for f in features_list]
                response.features.extend(f_objs)
                response.groups.append(
                    FeatureGroup(
                        id=f"{self._plugin_id}_group",
                        label="نتایج پردازش SDK",
                        features=f_objs,
                    )
                )
                has_features = True
            elif art.kind == "raster_ref":
                response.metadata["raster_path"] = art.payload.get("path")
                response.metadata["raster_meta"] = art.payload

        if has_features:
            response.user_message.summary = (
                f"پردازش SDK با موفقیت انجام شد. {len(response.features)} عارضه یافت شد."
            )
        else:
            response.user_message.summary = "پردازش SDK با موفقیت انجام شد."

        return response


class SDKPlugin(BasePlugin):
    """
    High-level Plugin class. Automates registry mappings and setup.
    """

    def __init__(self, manifest: PluginManifest | None = None) -> None:
        self._manifest = manifest or self._build_default_manifest()
        self._capabilities_regs: list[CapabilityRegistration] = []
        self._collect_capabilities()

    def _build_default_manifest(self) -> PluginManifest:
        return PluginManifest(
            id=self.__class__.__name__.lower(),
            version="0.1.0",
            name=self.__class__.__name__,
        )

    @property
    def manifest(self) -> PluginManifest:
        return self._manifest

    def _collect_capabilities(self) -> None:
        for _, attr in inspect.getmembers(self):
            reg = getattr(attr, "__geochat_capability__", None)
            if isinstance(reg, CapabilityRegistration):
                reg.func = attr
                self._capabilities_regs.append(reg)

    async def register(self, container) -> None:
        for reg in self._capabilities_regs:
            descriptor = reg.build_descriptor(self.id)
            container.capabilities.register(descriptor, replace=True)

            container.planners.register_planner(
                SDKPlanner(self.id, reg),
                replace=True,
            )

            container.step_handlers.register_handler(
                SDKStepHandler(self.id, reg),
                replace=True,
            )

        if self._capabilities_regs:
            container.fusions.register_fusion(
                SDKResultFusion(self.id),
                replace=True,
            )


def auto_collect(
    id: str,
    version: str = "0.1.0",
    name: str | None = None,
    description: str | None = None,
    author: str | None = None,
    permissions: list[Any] | None = None,
) -> SDKPlugin:
    """
    Collects all module-level decorated functions and bundles them into an SDKPlugin.
    """
    regs = list(_PENDING_CAPABILITIES)
    _PENDING_CAPABILITIES.clear()

    perm_list = []
    if permissions:
        for p in permissions:
            perm_list.append(p.value if hasattr(p, "value") else str(p))

    manifest = PluginManifest(
        id=id,
        version=version,
        name=name or id.replace("_", " ").title(),
        description=description,
        author=author,
        permissions=perm_list,
    )

    plugin = SDKPlugin(manifest)
    plugin._capabilities_regs.extend(regs)
    return plugin
